name: 'Assign Reviewers'
description: 'Assign and add approvers to github users specified in a configuration file'

inputs:
  assign-users:
    description: 'Add users as assignees on the PR'
    default: 'true'
    required: false
  request-reviews:
    description: 'Request PR reviews from component contributors'
    default: 'true'
    required: false
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  config-file:
    description: 'Path to a YAML configuration file'
    default: .github/assign_reviewers.yml
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
