name: 'Auto Assign'
on:
  pull_request:

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self action step
        uses: ./ # Uses an action in the root directory
