name: Assign Reviewers
on:
  # pull_request_target is needed instead of just pull_request
  # because repository write permission is needed to assign reviewers
  pull_request_target:

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Assign Reviewers
    steps:
      - uses: open-telemetry/assign-reviewers-action@main
