name: Assign Reviewers

on:
  # pull_request_target is needed instead of just pull_request
  # because repository write permission is needed to assign reviewers
  pull_request_target:

permissions:
  contents: read

jobs:
  run_self:
    permissions:
      contents: read
      pull-requests: write  # for assigning reviewers
    runs-on: ubuntu-latest
    name: Assign Reviewers
    steps:
      - uses: open-telemetry/assign-reviewers-action@main
