name: Ensure Dist Build
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run compile

      - name: Validate dist
        run: git diff --name-only --exit-code dist || (echo "Looks like dist doesn't match the source. Please ensure dist is built by running npm install and npm run compile" && exit 1)