name: Ensure Dist Build
on:
  push:
  pull_request:

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run compile

      - name: Validate dist
        run: git diff --name-only --exit-code diff || (echo "Looks like dist doesn't match the source. Please ensure dist is built by running npm run compile" && exit 1)